routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::resource('customers', 'CustomerController');

Route::resource('business', 'BusinessController');

Route::resource('users', 'UserController')->middleware('auth');

Route::post('business/changerole/{bid}/{rid?}','BusinessController@changerole')->name('user.changerole')->middleware('auth');
Route::post('business/indexgal/{rid?}','BusinessController@indexgal')->name('indexgal')->middleware('auth');
Route::post('business/CancellationApproval/{bid}/{rid?}','BusinessController@CancellationApproval')->name('user.CancellationApproval')->middleware('auth');

Route::get('business/statement_by_business/{bid?}','BusinessController@sta_by')->name('statement_by_business')->middleware('auth');
Route::get('customer/short','CustomerController@short')->name('customer.short')->middleware('auth');
Route::get('customer/customer_stataments_all','BusinessController@customer_stataments_all')->name('customer.customer_stataments_all')->middleware('auth');
Route::get('all_statement','BusinessController@sta')->name('business.all_statement')->middleware('auth');

Route::get('/usersStatmenteForm','UserController@usersStatmenteForm')->name('users.usersStatmenteForm')->middleware('auth');
Route::POST('add.user', '\App\Http\Controllers\Auth\RegisterController@adduser')->name('adduser')->middleware('auth');
#edit/delete users:
Route::get('user/deleteuser/{uid}', 'UserController@destroy')->name('user.delete')->middleware('auth');;
Route::get('user/edit_user/{cid}/{uid?}', 'UserController@editUser')->name('user.edit')->middleware('auth');;
#delete all users
Route::delete('myuserDeleteAll', 'UserController@deleteAll');

#user statements
Route::get('user/user_statement/{cid}', 'UserController@usersStatmentes')->name('user_statement')->middleware('auth');;
Route::get('myCard', 'BusinessController@myCard')->name('business.myCard')->middleware('auth');

Route::get('user/employee', 'UserController@back')->name('back')->middleware('auth');
Route::get('dashbord', 'UserController@usersDashbors')->name('users.dashbord')->middleware('auth');
Route::get('dashbordbus', 'BusinessController@businessDashbors')->name('business.dashbordbus')->middleware('auth');
Route::get('/', function () {

    return view('welcome');
})->name('root');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/downloadPDF','CustomerController@downloadPDF')->name('pdf');
Route::get('/logout', 'UserController@logout')->name('logout-home');

app/User.php
<?php

namespace App;
use Illuminate\Support\Facades\Auth;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','role_id','phone',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function role (){
        return $this->belongsTo('App\Role','role_id');
    } 
    public function isMinistryofHealth(){
        $uid = Auth::id();
        $user= User::findOrfail($uid);
        if($user->role_id===4) return true;
        return false;  
    }

    public function isManager(){
        $uid = Auth::id();
        $user= User::findOrfail($uid);
        if($user->role_id===1) return true;
        return false;  
    }
    public function isEmployee(){
        $uid = Auth::id();
        $user= User::findOrfail($uid);
        if($user->role_id===2) return true;
        return false;  
    }
    public static  function isOwner($uid){
        $user = Auth::user();
        $bid = $user->business_id; 
        $business = Business::findOrFail($bid);
        $oid= $business->owner_id;

        if($uid==$oid) return true;
        return false;  
    }

        public function business (){
        return $this->belongsTo('App\Business','id');
    }

    public function usersstatement (){
        return $this->hasMany('App\Usersstatement','user_id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;


use App\Business;
use App\Customer;
use App\User;
use App\Usersstatement;
use App\Role;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Hash;


class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['create','store']]);

    }
     public function index()
    {
        $user = Auth::user();
        $bid = $user->business_id; 
        $business = Business::findOrFail($bid);

        $users = User::where('business_id', $user->business_id)->paginate(8);
         #$users = User::paginate(2);
        return view('users.employee', compact('users','business'));    
    }

     
    
    public function usersStatmenteForm()
    {
        $user = Auth::user();
        #$userem = Usersstatement::all();
        return view('users.statement_form', compact('user'));    
    }
    
    public function usersStatmentes($id)
    {
        $user_statmentes = Usersstatement::where('user_id', $id)->orderBy('created_at','DESC')->paginate(10);


        #$userem = Usersstatement::all();
        return view('users.employee_statements', compact('user_statmentes'));    
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    public function store(Request $request)
    {
        $employee = new Usersstatement();

        if ($request->checkbox== TRUE){
            $employee = new Usersstatement();
            $employee -> user_id = Auth::id();
            $employee -> save();
             return redirect()->back()->with('success', 'statamate added successfully, you can add a new one  ');
            
      }else{
        return redirect()->back()->with('error', 'please confirm your health statamate');


      }


    }
    public function usersDashbors()
    {
        
        Gate::authorize('check-both');
        $users = Auth::user();
               
        return view('users.dashbord', compact('users'));    
    }



    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);

        $roles = Role::where('id', 1)->orWhere('id', 2)->get();
        
        return view('users.employee_edit' , compact('user','roles'));    }

        
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);
        $user->name = $request->name;
        $user->phone = $request->phone;
        $user->email = $request->email;
        $user->password = Hash::make($request->password); 
        $user->role_id = $request->role_id;
        $user->save();


        return redirect('users');    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete(); 
        return redirect('users');    }

    public function deleteAll(Request $request)
    {
        $ids = $request->ids;
        DB::table("users")->whereIn('id',explode(",",$ids))->delete();
        return response()->json(['success'=>" The Employees Deleted Successfully "]);
    }

    public function back()
    {
        return redirect('users');
    }

    public function logout () {
        //logout user
        auth()->logout();
        // redirect to homepage
        return view('welcome');  
      
    }


}

resources/views/users/dashbord.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>  

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
   

    <!-- Styles -->
	<link href="{{ asset('css/app.css') }}" rel="stylesheet">
	@php
 $user= Illuminate\Support\Facades\Auth::user();
 @endphp

</head>
<body>

<div class="card text-center  mb-10 margin-1">
        <div class="card-header">
		<a href = "{{ route('logout')}}"  class="btn btn-danger btn-sm float-right" style="font-weight: bold; float:right;margin-right: 20px;">Logout</a>

        <h1 style="margin-left: 70px;">Corona Statement System</h1>
        </div>
        <div class="card-body">
        <h3 class="card-title"> Welcome {{ Auth::user()->name }}</h3>
        
		@can('check-manager') 
		<a href =  "{{url('users')}}" class="btn btn-light btn-outline-dark btn-lg">Employees List </a>

        <a href =  "{{url('customers')}}" class="btn btn-light btn-outline-dark btn-lg">Customers Health Stataments</a>
        <p><p><a href =  "{{ route('register') }}" class="btn btn-light btn-outline-dark btn-lg">Add New Employes</a>
        @endcan
 <a href =  "{{url('usersStatmenteForm')}}" class="btn btn-light btn-outline-dark btn-lg">Add Your Own Statement</a>
		<a href =  "{{ route('user_statement', $user->id) }}" class="btn btn-light btn-outline-dark btn-lg">Your Health Stataments History</a></p></p>
		<a href =  "{{url('myCard')}}" class="btn btn-light btn-outline-dark btn-lg">Buisness Info</a>

        
        <div class="box">
    <div class="container">
     	<div class="row">
			 
			    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
               
					<div class="box-part text-center">
                        
                    <img src="https://i.ibb.co/fHGxMbL/2020-10-14-024856.png" alt="2020-10-14-024856" border="0"></a>
                        
						<div class="title">
							<h4>Wear a mask</h4>
						</div>
                        
						<div class="text">
							<span>Please keep wear a mask as long as you are not at your table.</span>
						</div>
                        
						                       
					 </div>
				</div>	 
				
				 <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
               
					<div class="box-part text-center">
					    
					    <img src="https://i.ibb.co/9WRsh1d/2020-10-14-024158.png" alt="2020-10-14-024158" border="0"></a>
                    
						<div class="title">
							<h4>Measure heat</h4>
						</div>
                        
						<div class="text">
							<span>On the business entering, you have to measure heat.
 A person who has more than 38 degrees, can not enter!</span>
						</div>
                        
						                        
					 </div>
				</div>	 
				
				 <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
               
					<div class="box-part text-center">
                        
                    <img src="https://i.ibb.co/wK15Rcp/2020-10-14-024133.png" alt="2020-10-14-024133" border="0"></a>
                        
						<div class="title">
							<h4>keep distance</h4>
						</div>
                        
						<div class="text">
							<span>Please be sure to keep a distance from other guests.</span>
						</div>
                        
						
					 </div>
				</div>	
				 
		
		</div>		
    </div>
</div>


</div> </body>
</html>

resources/views/users/statement_form.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>



@php
 $user= Illuminate\Support\Facades\Auth::user();
 @endphp


   <!-- ####################################   Settings  ########################################   -->


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>



<link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="../assets/img/favicon.png">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
Health Stataments Supervision   </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
   <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <!-- Styles -->
    <link href="{{ asset('assets/css/bootstrap.min.css') }}" rel="stylesheet" />
  <link href="{{ asset('assets/css/paper-dashboard.css')}}" rel="stylesheet" />
</head>




<body class="">
    <div class="wrapper">
        <div class="sidebar" data-color="white" data-active-color="danger">
            <div  class="logo" style='margin-left:auto; margin-right:auto'>
            <img style='position: relative;right: 5px;' src="{{URL::asset('assets/img/logo.png')}}" alt="profile Pic"  width="350">
        </div>

                                <!-- ##########   Sidebar  ############   -->

      <div style="text-align:left" class="sidebar-wrapper">
        <ul class="nav">

        @can('check-ministry') 
        <li >

            <a href="{{ route('business.index') }}">
              <i class="nc-icon nc-icon nc-bank"></i>
              <p >All Business</p>
            </a>
          </li>
          @endcan
          @can('check-manager') 

        <li >
            <a href="{{ route('users.index') }}">
              <i class="nc-icon nc-single-02"></i>
              <p >Employees</p>
            </a>
          </li>
          @endcan

          @can('check-ministry') 

          <li>

          <a  href="{{ route('business.all_statement')}}">
              <i class="nc-icon nc-paper"></i>
              <p >All Customers Stataments</p>
            </a>
            </li>
          @endcan

          @can('check-manager') 
          <li>

            <a  href="{{ route('customers.index') }}">
              <i class="nc-icon nc-paper"></i>
              <p >Customers Stataments</p>
            </a>
          </li>
          @endcan

          <li class="active ">
            <a href="{{ route('users.usersStatmenteForm') }}">
              <i class="nc-icon nc-simple-add"></i>
              <p>Add Own Statement</p>
            </a>
          </li>

          <li>
            <a href="{{ route('user_statement', $user->id) }}">
              <i class="nc-icon nc-circle-10"></i>
              <p>Your Stataments</p>
            </a>
          </li>
          @can('check-both') 
          <li>
            <a href="{{ route('business.myCard') }}">
              <i class="nc-icon nc-alert-circle-i"></i>
              <p>Contact Details</p>
            </a>
          </li>
          @endcan

          
          @can('check-ministry') 
          <li>
            <a href="{{ route('business.dashbordbus') }}">
              <i class="nc-icon nc-tv-2"></i>
              <p>Back To Dashboard</p>
            </a>
          </li>
          @endcan

          @can('check-both') 
          <li>
            <a href="{{ route('users.dashbord') }}">
              <i class="nc-icon nc-tv-2"></i>
              <p>Back To Dashboard</p>
            </a>
          </li>
          @endcan

          
        </ul>
      </div>
    </div>


                                <!-- ##########   Main Panel  ############   -->


<div class="main-panel" style="   height: 100vh;">
    <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
            <div class="container-fluid">
            <div class="navbar-wrapper">
         
            @php
            @endphp
            @if (Auth::guest())


            <a class="navbar-brand" href="javascript:;"> Welcome Guest</a>
            @else

            <a class="navbar-brand" href="javascript:;"> Welcome Dear {{$user->name}}</a>
            @endif

          </div>
       
          
          <div class="collapse navbar-collapse justify-content-end" id="navigation">
         

            <ul class="navbar-nav">
              <li class="nav-item btn-rotate dropdown">
                <a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="nc-icon nc-settings-gear-65 "style="font-size: 1.3rem;"></i>
                  <p>
                    <span class="d-lg-none d-md-block">Some Actions</span>
                  </p>
                </a>
                
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                @guest

                  <a class="dropdown-item" href="{{ route('login') }}">{{ __('Login') }}</a>
                  @else
                  <a class="dropdown-item" href="{{ route('logout') }}">{{ __('Logout') }}</a>
                  @endguest

                </div>

              </li>
            </ul>
          </div>
        </div>
      </nav>


      
           <!-- End Navbar -->
           <div class="content" style=' max-width: 1500px; display: block; margin-left: auto; margin-right: auto;'>
        <div class="row">
          <div class="col-md-12">
            <div class="card">
           

          <main class="py-4" style="">









           <!-- CONTEENT -->

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Employee Health Statement') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('users.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Full Name') }}</label>
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ $user->name}}</label>

                            
                        </div>

                        <div class="form-group row">
                            <label for="phone" class="col-md-4 col-form-label text-md-right">{{ __('Phone Number') }}</label>
                            <label for="phone" class="col-md-4 col-form-label text-md-right">{{ $user->phone }}</label>

                           
                        </div>

                        <div class="form-group row">
                            <label for="phone" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail') }}</label>
                            <label for="phone" class="col-md-4 col-form-label text-md-right">{{ $user->email }}</label>
                        </div>

                        <div class="form-group row">
                            <label for="phone" class="col-md-4 col-form-label text-md-right">{{ __('Role') }}</label>
                            <label for="phone" class="col-md-4 col-form-label text-md-right">{{ $user->role->name }}</label>

                           
                        </div>

                    


          
                        Please note that this certificate is a health Statement
<br><br>
<P>1. I'm not coughing</P> 
<P>2. As far as I know, my temperature is not over 38, and I didn't have fever in the last week</P> 
<P>3. I wasn't in touch with Covid-19 patient</P> 




                    <input type="checkbox" id="checkbox" name="checkbox" >
                    <label for="checkbox"> Confirm</label><br>
                    
                    @if (session('error'))
    <div class="alert alert-danger text-center msg" id="error">
    <strong>{{ session('error') }}</strong>
    </div>
@endif

@if (session('success'))
    <div class="alert alert-success text-center msg" id="success">
    <strong>{{ session('success') }}</strong>
    </div>
@endif



                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary btn-round">
                                    {{ __('Accept') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>











</main></div></div></div></div>
   


        
   <footer class="footer" style="position: absolute; bottom: 0; width: -webkit-fill-available;">
     <div class="container-fluid">
       <div class="row">
         <nav class="footer-nav">
           <ul>
             <li><a  target="_blank">Demo Release - CORONA Supervision System </a></li>
     
           </ul>
         </nav>
         <div class="credits ml-auto">
           <span class="copyright">
             © 2020, made with <i class="fa fa-heart heart"></i> by Evgeni, Adi, Shahar and Gal
           </span>
         </div>
       </div>
     </div>
   </footer>
 </div>
</div>
<!--   Core JS Files   -->
<script src="./assets/js/core/jquery.min.js"></script>
<script src="./assets/js/core/popper.min.js"></script>
<script src="./assets/js/core/bootstrap.min.js"></script>
<script src="./assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
<!--  Google Maps Plugin    -->
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
<!-- Chart JS -->
<script src="./assets/js/plugins/chartjs.min.js"></script>
<!--  Notifications Plugin    -->
<script src="./assets/js/plugins/bootstrap-notify.js"></script>
<!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
<script src="./assets/js/paper-dashboard.min.js?v=2.0.1" type="text/javascript"></script>


<script>
 function SelectText(element) {
   var doc = document,
     text = element,
     range, selection;
   if (doc.body.createTextRange) {
     range = document.body.createTextRange();
     range.moveToElementText(text);
     range.select();
   } else if (window.getSelection) {
     selection = window.getSelection();
     range = document.createRange();
     range.selectNodeContents(text);
     selection.removeAllRanges();
     selection.addRange(range);
   }
 }
 window.onload = function() {
   var iconsWrapper = document.getElementById('icons-wrapper'),
     listItems = iconsWrapper.getElementsByTagName('li');
   for (var i = 0; i < listItems.length; i++) {
     listItems[i].onclick = function fun(event) {
       var selectedTagName = event.target.tagName.toLowerCase();
       if (selectedTagName == 'p' || selectedTagName == 'em') {
         SelectText(event.target);
       } else if (selectedTagName == 'input') {
         event.target.setSelectionRange(0, event.target.value.length);
       }
     }

     var beforeContentChar = window.getComputedStyle(listItems[i].getElementsByTagName('i')[0], '::before').getPropertyValue('content').replace(/'/g, "").replace(/"/g, ""),
       beforeContent = beforeContentChar.charCodeAt(0).toString(16);
     var beforeContentElement = document.createElement("em");
     beforeContentElement.textContent = "\\" + beforeContent;
     listItems[i].appendChild(beforeContentElement);

     //create input element to copy/paste chart
     var charCharac = document.createElement('input');
     charCharac.setAttribute('type', 'text');
     charCharac.setAttribute('maxlength', '1');
     charCharac.setAttribute('readonly', 'true');
     charCharac.setAttribute('value', beforeContentChar);
     listItems[i].appendChild(charCharac);
   }
 }
</script>

</body>
</html>